server:
  port: 8897

debug: true

spring:
  #Monogo DB connection
  data:
    mongodb:
      database: sample_mflix
      uri: mongodb+srv://m220student:m220password@m220.dp7vh.mongodb.net/sample_mflix?retryWrites=true&w=majority